# Site settings
title: Serge Lobatch
email: serge.lobatch@gmail.com
description: "the first and only official personal site of serge lobatch"
baseurl: "http://sergelobatch.com"
#baseurl: ""
url: ""

# Default build settings
markdown: kramdown
# permalink: /slog/

# Serge's build settings
permalink: /slog/:year/:i_month/:i_day/:title

# Sass directory
sass:
  sass_dir: _sass

# Plugins
gems:
  - jekyll-redirect-from
