# Site settings
title: Serge Lobatch
email: serge.lobatch@gmail.com
description: "the first and only official personal site of serge lobatch"
baseurl: ""
url: "http://slobatch.github.io"

# Build settings
markdown: kramdown
permalink: pretty
